language: python

python: 
  - "2.7"
  - "3.5"
  
install:
  - pip install codecov
  - pip install -r requirements-dev.txt
  
script:
  - python -m pytest --cov=./ --cov-report term-missing --cov-config=.coveragerc ./tests

after_success:
- codecov
